pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh "/opt/apache-maven-3.9.4/bin/mvn -B -DskipTests clean package"
            }
        }
        stage('Test') {
            steps {
                sh "/opt/apache-maven-3.9.4/bin/mvn test"
            }
            post {
                always {
                    junit "target/surefire-reports/*.xml"
                }
            }
        }
        stage('Deliver') {
            steps {
                sh "./jenkins/scripts/deliver.sh"
            }
        }
        stage('Extra') {
            steps {
                echo "Another stage"
            }
        }

        stage('Another Extra') {
            steps {
                echo "Another extra stage"
            }
        }
    }
}
